"""Export utilities for generating CSV, JSON, and summary reports."""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = ROOT / "outputs"


def export_csv(df: pd.DataFrame, filename: str = "review_queue.csv") -> Path:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUTPUT_DIR / filename
    df.to_csv(path, index=False)
    return path


def export_json(df: pd.DataFrame, filename: str = "review_queue.json") -> Path:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUTPUT_DIR / filename
    records = df.to_dict(orient="records")
    path.write_text(json.dumps(records, indent=2, default=str), encoding="utf-8")
    return path


def export_summary_md(df: pd.DataFrame, filename: str = "demo_summary.md") -> Path:
    """Generate a markdown summary of the review queue."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUTPUT_DIR / filename

    total = len(df)
    high = int((df.get("priority", pd.Series()) == "High").sum()) if "priority" in df.columns else 0
    medium = int((df.get("priority", pd.Series()) == "Medium").sum()) if "priority" in df.columns else 0
    low = int((df.get("priority", pd.Series()) == "Low").sum()) if "priority" in df.columns else 0

    lines = [
        "# Review Queue Summary",
        "",
        f"- Total reports: {total}",
        f"- High priority: {high}",
        f"- Medium priority: {medium}",
        f"- Low priority: {low}",
        "",
        "## Notes",
        "",
        "- This summary was generated by the Species Report Quality Assistant prototype.",
        "- All species suggestions are candidate labels only and require human confirmation.",
        "- No internal HRI/CSSC data was used.",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def dataframe_to_csv_bytes(df: pd.DataFrame) -> bytes:
    return df.to_csv(index=False).encode("utf-8")


def dataframe_to_json_bytes(df: pd.DataFrame) -> bytes:
    return json.dumps(df.to_dict(orient="records"), indent=2, default=str).encode("utf-8")
